name: flutter_artist_vibe_theme
description: A premium thematic extension for FlutterArtist that provides advanced multi-layered aesthetic styles, including Glassmorphism, Neumorphism, and High Contrast layouts.
version: 0.8.1
resolution: workspace
homepage: https://o7planning.github.io

environment:
  sdk: ^3.11.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_artist_core: ^1.0.0
  flutter_artist_styles: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
flutter:

# -------------------------------------------------------
# dependency_overrides:
# -------------------------------------------------------